name: Bug Report
description: Report a bug on ClawDex
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: "Describe the bug..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: "What should have happened instead?"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Page URL
      placeholder: "https://www.clawdex.io/..."
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: "Screenshots, console errors, etc."
